version: '3.9'

services:
  ai-article-summary:
    build:
      context: .
      args:
        HOST: ${HOST}
        PORT: ${PORT}
    image: ai-article-summary-image
    container_name: ai_summary_container
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
